# Generated by Django 5.2.17 on 2026-08-08 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'merchant',
            },
        ),
        migrations.CreateModel(
            name='StatusMerchant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'status_merchant',
            },
        ),
        migrations.CreateModel(
            name='MerchantStatusHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField(null=True)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(db_column='id_merchant', on_delete=django.db.models.deletion.PROTECT, to='merchant.merchant')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('status_anterior', models.ForeignKey(db_column='status_anterior', on_delete=django.db.models.deletion.PROTECT, related_name='historicos_status_anterior', to='merchant.statusmerchant')),
            ],
            options={
                'db_table': 'merchant_status_history',
            },
        ),
        migrations.AddField(
            model_name='merchant',
            name='status',
            field=models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='merchant.statusmerchant'),
        ),
    ]
